### ISSUE TITLE
MPAS Configuration & Validation V2

### ISSUE THREAD

**Issue by phoban01** [open-component-model/mpas-product-controller#55]
## Description

Issue #45 outlines a proposal with respect to improving configuration and validation.

## Requirements

- [ ]  Update `ProductDescription `   to take schema.cue (this replaces both the readme and validation rules)
- [ ]  Update the Product controller to generate a config.cue and README from schema.cue files when generating products (this replaces values.yaml and README)
- [ ]  Update the Product controller to use the schema.cue file to validate the config.cue (this replaces the use of rego and OPA library)
- [ ]   When a product PR is merged "unify" the schema.cue with te valid config.cue and store the result as yaml in a configmap which is read by the Configuration controller.

## Implementation

See #45 for details of the implementation. The CUE Go API can be used for validation and generation.

#45 does not address the issue of combining configuration and schema for multiple items in a product. This should be straightforward to handle using the CUE API.

**Comment by souleb** [comment]
#89
